@startuml

!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()


Person(reiziger, "Reiziger", "Klant bij TripTop die een reis plant, boekt en beheerd.")

System(triptop, "TripTop Systeem", "Systeem om een reis in te plannen, boeken en beheren.")

System_Ext(idprovider, "Identity Provider (Google, Microsoft, etc.)", "")
System_Ext(payprovider, "Betalings Provider", "")
System_Ext(sleepprovider, "Overnachting Provider (Booking.com, Airbnb, etc.)", "")
System_Ext(tripprovider, "Vervoer Provider (KLM, Uber, NS, etc.)", "")
System_Ext(rentprovider, "Verhuur Provider (Sixt, Hertz, etc.)", "")
System_Ext(activityprovider, "Activiteit Provider (GetYourGuide, TripAdvisor, etc.)", "")
System_Ext(foodprovider, "Eten en drinken Provider (TakeAway, UberEats, etc.)", "")

Rel(reiziger, triptop, "", "")
Rel(triptop, idprovider, "", "")
Rel(triptop, payprovider, "", "")
Rel(triptop, sleepprovider, "", "")
Rel(triptop, tripprovider, "", "")
Rel(triptop, rentprovider, "", "")
Rel(triptop, activityprovider, "", "")
Rel(triptop, foodprovider, "", "")




@enduml