@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_TOP_DOWN()

Container_Boundary(cb, "Backend") {
    Component(expenseController, "ExpenseController", "Spring Boot")
    Component(expenseService, "ExpenseService", "Expense Service")
   Component(expenseDao, "ExpenseDao", "Data Access")


    Component(authController, "AuthenticationController", "Spring Boot")
    Component(authService, "AuthenticationService", "Authentication Service")
    Component(userDao, "UserDao", "UserDao")
}

    ComponentDb(db, "Database")

  Rel(expenseController, expenseService, "Relatie")
  Rel(expenseService, expenseDao, "Relatie")
  Rel(expenseDao, db, "Relatie")

  Rel(authController, authService, "Relatie")
  Rel(authService, userDao, "Relatie")
  Rel(userDao, db, "Relatie")

LAYOUT_TOP_DOWN()

@enduml
