@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

skinparam ranksep 80
skinparam nodesep 100
skinparam ArrowColor #666666
skinparam linetype ortho
skinparam ArrowFontSize 12
skinparam ArrowFontColor black
skinparam ArrowFontStyle bold
skinparam ArrowFontName Arial

LAYOUT_TOP_DOWN()

Container(frontend, "Web Applicatie", "React js")

Container_Boundary(cb, "Backend") {
    Component(tripcontroller, "TripController", "Spring Boot controller")
    Component(tripservice, "TripService", "Spring Boot service")
    Component(stayadapter, "VerblijfAdapter", "Spring Boot adapter")
    Component(triprepository, "TripRepository", "Spring Boot repository")
}

together{
    System_Ext(stay, "Overnachting API (Booking.com, Airbnb)", "Bied overnachtingen")
    ComponentDb(db, "Database", "MongoDB")
}

    Rel(frontend, tripcontroller, "Gebruikt")
    Rel(tripcontroller, tripservice, "Gebruikt")
    Rel(tripservice, stayadapter, "Gebruikt")
    Rel(stayadapter, stay, "Gebruikt")

    Rel(tripservice, triprepository, "Gebruikt")
    Rel(triprepository, db, "Gebruikt")

@enduml
