@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

skinparam ranksep 80
skinparam nodesep 100
skinparam ArrowColor #666666
skinparam linetype ortho
skinparam ArrowFontSize 12
skinparam ArrowFontColor black
skinparam ArrowFontStyle bold
skinparam ArrowFontName Arial

LAYOUT_TOP_DOWN()

Container(frontend, "Web Applicatie", "React js")

Container_Boundary(cb, "Backend") {
    Component(tripcontroller, "tripController", "Spring Boot controller")
    Component(tripservice, "tripService", "Spring Boot service")
    Component(stayadapter, "stayAdapter", "Spring Boot adapter")
    Component(triprepository, "tripRepository", "Spring Boot repository")
}

together{
    System_Ext(stay, "Overnachting API (Booking.com, Airbnb)", "Bied overnachtingen")
    ComponentDb(db, "Database")
}

    Rel(frontend, tripcontroller, "")
    Rel(tripcontroller, tripservice, "")
    Rel(tripservice, stayadapter, "")
    Rel(stayadapter, stay, "")

    Rel(tripservice, triprepository, "")
    Rel(triprepository, db, "")

@enduml
