@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Opmaak voor netheid, rechte lijnen en betere tekstzichtbaarheid
skinparam ranksep 80
skinparam nodesep 100
skinparam ArrowColor #666666
skinparam linetype ortho

' Tekst opmaak verbeteren
skinparam ArrowFontSize 12
skinparam ArrowFontColor black
skinparam ArrowFontStyle bold
skinparam ArrowFontName Arial

title Container diagram - Triptop

SHOW_PERSON_OUTLINE()

' Gebruikers
Person(reiziger, "Reiziger", "Een gebruiker die TripTop wil gebruiken voor het plannen van een reis")
Person(reisagent, "Reis Agent", "Een gebruiker die reizigers ondersteunt bij het plannen van hun reis")

' Externe systemen in logische groepen

together{
System_Ext(googleMapsApi, "Google Maps API", "Biedt navigatie en locatiegegevens")
System_Ext(weerApi, "Open Weather API", "Geeft weerinformatie voor specifieke locaties")
}

together {
  System_Ext(nsApi, "NS API", "Informatie over openbaar vervoer en het boeken van ritten")
  System_Ext(overnachtingApi, "Overnachting API (Booking.com, Airbnb)", "Voor het vinden en boeken van accommodaties")
  System_Ext(vluchtApi, "Vluchten API (Skyscanner, Google flights)", "Voor het vinden en boeken van vluchten")
}

together{
System_Ext(identityApi, "Identity Provider API (WireMock)", "Simuleert identity provider")
System_Ext(betalingApi, "Betaling API (?)", "Voor het verwerken van betalingen")
}
' TripTop Systeem
System_Boundary(tripTopSystem, "TripTop"){
    Container(webApp, "Web Applicatie", "? (React)", "Helpt reizigers bij het plannen en boeken van reizen")
    Container(backendService, "Backend", "Springboot Java", "Verwerkt data en beheert bedrijfslogica")
    Container(dataStore, "Database", "SQL of NOSQL?", "Slaat gebruikersgegevens en geboekte reizen op")
}

' Gebruikersinteracties
Rel(reiziger, webApp, "Gebruikt", "HTTPS")
Rel(reisagent, webApp, "Ondersteunt via", "HTTPS")

' Interne systeemrelaties
Rel(webApp, backendService, "API requests", "HTTPS")
Rel(backendService, dataStore, "CRUD operaties", "Database toegang")

' Web App naar informatie APIs
Rel(webApp, googleMapsApi, "Navigatie", "HTTPS/REST")
Rel(webApp, weerApi, "Weer info", "HTTPS/REST")
Rel(webApp, nsApi, "Krijgt Vertrektijden", "HTTPS/REST")
Rel(webApp, overnachtingApi, "Krijgt Accommodaties", "HTTPS/REST")
Rel(webApp, vluchtApi, "Krijgt vluchten", "HTTPS/REST")

' Authentication
Rel(webApp, identityApi, "Authenticatie", "HTTPS")
Rel(backendService, identityApi, "Autorisatie", "HTTPS")

' Backend naar boekings-APIs
Rel(backendService, nsApi, "Boekt reizen", "HTTPS/REST")
Rel(backendService, overnachtingApi, "Boekt verblijf", "HTTPS/REST")
Rel(backendService, vluchtApi, "Boekt vluchten", "HTTPS/REST")
Rel(backendService, betalingApi, "Betalingen", "HTTPS/REST")

@enduml