@startuml
title "Container diagram TripTop"

!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()


Person(reiziger, "Reiziger", "Klant bij TripTop die een reis plant, boekt en beheerd.")
Person(reisagent, "Reisagent", "Reisagent die bij TripTop klanten helpt bij het plannen van een reis")

System_Boundary(c1, "TripTop Platform") {

Container(webapp, "Web Applicatie", "React js", "Bied de gebruikersinterface voor klanten en reisagenten.")
Container(backend, "Backend", "Spring boot", "Behandelt de bedrijfslogica")
Container(database, "Database", "?", "Slaat alle gebruikersgegevens, reizen en boekingen op")

}

System_Ext(idprovider, "Identity Provider (WireMock)", "Verwerkt gebruikers authenticatie")
System_Ext(ns, "NS API", "Bied treinreis informatie")
System_Ext(maps, "Google Maps Api", "Bied route en locatietracking")
System_Ext(stay, "Overnachting API (Booking.com, Airbnb)", "Bied overnachtingen")
System_Ext(flight, "Vlucht API (Google Flights, Skyscanner)", "Bied vluchtinformatie")
System_Ext(payment, "Betaling Provider (Stripe, Adyen, Mollie)", "Verwerkt betalingen")
System_Ext(weather, "Weer API (Open Weather)", "Bied weerinformatie")

Rel(reiziger, webapp, "Gebruikt om reizen te plannen, boeken en beheren", "HTTPS")
Rel(reisagent, webapp, "Gebruikt om klanten bij te staan", "HTTPS")
Rel(webapp, backend, "Verstuurt API requests naar", "HTTPS")
Rel(backend, database, "Leest en schrijft gegevens naar", "?")

Rel(webapp, idprovider, "Verifieert gebruikers via", "HTTPS/OAuth 2.0")
Rel(backend, ns, "Haalt treinreisinformatie op van", "HTTPS")
Rel(webapp, maps, "Verkrijgt route- en locatiegegevens van", "HTTPS")
Rel(backend, stay, "Zoekt en boekt overnachtingen via", "HTTPS")
Rel(backend, flight, "Zoekt en boekt vluchten via", "HTTPS")
Rel(backend, payment, "Verwerkt betalingen via", "HTTPS")
Rel(webapp, weather, "Haalt weersverwachtingen op van", "HTTPS")

@enduml