@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

skinparam ranksep 80
skinparam nodesep 100
skinparam ArrowColor #666666
skinparam linetype ortho

skinparam ArrowFontSize 12
skinparam ArrowFontColor black
skinparam ArrowFontStyle bold
skinparam ArrowFontName Arial

title Componentendiagram - TripTop

Person(reiziger, "Reiziger", "Een gebruiker die TripTop wil gebruiken voor het plannen van een reis")
Person(reisagent, "Reisagent", "Een gebruiker die reizigers ondersteunt bij het plannen van hun reis")

Container_Boundary(cb, "Webapplicatie") {
together{
Component(loginform, "Inlogformulier")
Component(loginPage, "Inlogpagina")
}

together{
Component(homePage, "Homepagina")
Component(homeMessage, "Homebericht")
}

together{
Component(tripOverview, "Reisoverzicht")
Component(bookingPage, "Boekingspagina")
Component(bouwsteenHolder, "Bouwsteenhouder")
Component(bouwsteen, "Bouwsteen")
Component(map, "Kaart")
Component(bouwsteenDetail, "Bouwsteendetails")
Component(categoryLabel, "Categorie-label")
Component(resevationForm, "Reserveringsformulier")
}

together{
Component(accountPage, "Accountpagina")
Component(accountMenu, "Accountmenu")
Component(accountLink, "Accountlink")
Component(bookedTrips, "Geboekte reizen")
}

together{
Component(reisAgentPage, "Reisagentpagina")
Component(reisAgentDashboard, "Reisagent-dashboard")
Component(pendingTrips, "In afwachting reizen")
}

together{
Component(betalingsPage, "Betalingspagina")
Component(orderOverview, "Bestellingsoverzicht")
Component(gegevensForm, "Gegevensformulier")
}

together{
Component(router, "Router")
Component(app, "App")
Component(navbar, "Navigatiebalk")
Component(footer, "Voettekst")
}

Component(searchbar, "Zoekbalk")

}

together{
System_Ext(googleMapsApi, "Google Maps API", "Biedt navigatie en locatiegegevens")
System_Ext(weerApi, "Open Weather API", "Geeft weerinformatie voor specifieke locaties")
System_Ext(nsApi, "NS API", "Levert OV-informatie en boekingsopties")
System_Ext(overnachtingApi, "Overnachting API (Booking.com, Airbnb)", "Voor het vinden en boeken van accommodaties")
System_Ext(vluchtApi, "Vluchten API (Skyscanner, Google Flights)", "Voor het vinden en boeken van vluchten")
System_Ext(identityApi, "Identity Provider API (WireMock)", "Simuleert een identity provider")
}

' Systeem externe relaties
Rel(bookingPage, searchbar, "Maakt gebruik van")
Rel(bouwsteenHolder, weerApi, "Haalt weersvoorspellingen op bij")
Rel(bouwsteenHolder, nsApi, "Haalt treininformatie op bij")
Rel(bouwsteenHolder, overnachtingApi, "Haalt accommodatie-informatie op bij")
Rel(bouwsteenHolder, vluchtApi, "Haalt vluchtinformatie op bij")
Rel(loginform, identityApi, "Controleert identiteit via")

Rel(map, googleMapsApi, "Haalt geolocatie-informatie op bij")

' Gebruikersrelaties
Rel(reiziger, app, "Maakt gebruik van")
Rel(reisagent, app, "Maakt gebruik van")

' Applicatiestructuur
Rel(app, router, "Maakt gebruik van")
Rel(app, navbar, "Maakt gebruik van")
Rel(app, footer, "Maakt gebruik van")

Rel(router, homePage, "Routeert naar")
Rel(router, loginPage, "Routeert naar")
Rel(router, bookingPage, "Routeert naar")
Rel(router, accountPage, "Routeert naar")
Rel(router, reisAgentPage, "Routeert naar")
Rel(router, betalingsPage, "Routeert naar")

Rel(homePage, homeMessage, "Bevat")
Rel(homePage, searchbar, "Bevat")

Rel(accountPage, accountMenu, "Bevat")
Rel(reisAgentPage, reisAgentDashboard, "Bevat")

Rel(reisAgentDashboard, pendingTrips, "Toont")

Rel(bookingPage, bouwsteenHolder, "Bevat")
Rel(bookingPage, map, "Bevat")
Rel(bookingPage, categoryLabel, "Bevat")

Rel(bouwsteenHolder, bouwsteen, "Bevat")
Rel(bouwsteen, bouwsteenDetail, "Toont details van")

Rel(accountMenu, accountLink, "Bevat")
Rel(accountMenu, bookedTrips, "Bevat")
Rel(loginPage, loginform, "Bevat")

Rel(bookingPage, resevationForm, "Bevat")
Rel(bookingPage, tripOverview, "Bevat")

Component(be, "Back-end")

@enduml
