@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

skinparam ranksep 80
skinparam nodesep 100
skinparam ArrowColor #666666
skinparam linetype ortho
skinparam ArrowFontSize 12
skinparam ArrowFontColor black
skinparam ArrowFontStyle bold
skinparam ArrowFontName Arial

LAYOUT_TOP_DOWN()

Container(frontend, "Web Applicatie", "React js")

Container_Boundary(cb, "Backend") {
    Component(logincontroller, "loginController", "Spring Boot controller")
    Component(tripcontroller, "tripController", "Spring Boot controller")
    Component(loginservice, "loginService", "Spring Boot service")
    Component(tripservice, "tripService", "Spring Boot service")
    Component(loginadapter, "loginAdapter", "Spring Boot adapter")
    Component(flightadapter, "VluchtAdapter", "Spring Boot adapter")
    Component(trainadapter, "TreinAdapter", "Spring Boot adapter")
    Component(stayadapter, "VerblijfAdapter", "Spring Boot adapter")
    Component(paymentadapter, "BetalingsAdapter", "Spring Boot adapter")
    Component(triprepository, "tripRepository", "Spring Boot repository")
}

together{
    System_Ext(idprovider, "Identity Provider", "Wiremock")
    System_Ext(ns, "NS API", "Bied treinreis informatie")
    System_Ext(stay, "Overnachting API (Booking.com, Airbnb)", "Bied overnachtingen")
    System_Ext(flight, "Vlucht API (Google Flights, Skyscanner)", "Bied vluchtinformatie")
    System_Ext(payment, "Betaling Provider (Stripe, Adyen, Mollie)", "Verwerkt betalingen")

    ComponentDb(db, "Database", "MongoDB NOSQL")

}

  Rel(frontend, logincontroller, "HTTP/REST aanroepen voor authenticatie")
  Rel(frontend, tripcontroller, "HTTP/REST aanroepen voor reisbeheer")

  Rel(logincontroller, loginservice, "Gebruikt voor gebruikersauthenticatie")
  Rel(tripcontroller, tripservice, "Gebruikt voor reisoperaties")

  Rel(tripservice, loginservice, "Valideert gebruikersrechten")

  Rel(tripservice, flightadapter, "Boekt vluchten")
  Rel(tripservice, trainadapter, "Beokte treinen")
  Rel(tripservice, stayadapter, "Boekt accomodaties")
  Rel(tripservice, paymentadapter, "Initieert betalingstransacties")
  Rel(trainadapter, ns, "Roept NS API aan")
  Rel(stayadapter, stay, "Roept accomodatie API aan")
  Rel(flightadapter, flight, "Roept vluchten api aan")
  Rel(paymentadapter, payment, "Verwerkt betalingen")

  Rel(tripservice, triprepository, "Bewaart en haalt reisgegevens op")
  Rel(triprepository, db, "CRUD operaties")

  Rel(loginservice, loginadapter, "Delegeert authenticatie")
  Rel(loginadapter, idprovider, "Verifieert inloggegevens")



@enduml
